const data = [
  {
    title: "Sản phẩm Dây truyền động",
    type: 1,
    data: [
      {
        id: 1,
        name: "GF-10",
        img: "./img/products/DayTruyenDong/GF-10_.jpg",
        children: [
          {
            idProduct: 1,
            name: "GF-10",
            img: "./img/products/DayTruyenDong/GF-10.jpg",
            img2: "./img/products/DayTruyenDong/GF-10_.jpg",
            key: "GF-10",
            thickness: "1.0 mm",
            width: "200 mm",
          },
        ],
        type: 2,
      },
      {
        id: 2,
        name: "HS-5",
        img: "./img/products/DayTruyenDong/HS-5.jpg",
        children: [
          {
            idProduct: 2,
            name: "HS-5",
            img2: "./img/products/DayTruyenDong/HS-5.jpg",
            img: "./img/products/DayTruyenDong/HS-5(1).jpg",
            key: "HS-5",
            thickness: "0.7 mm",
            width: "120 mm",
          },
        ],
        type: 2,
      },
      {
        id: 3,
        name: "W-8",
        img: "./img/products/DayTruyenDong/W-8.jpg",
        children: [
          {
            idProduct: 3,
            name: "W-8",
            img2: "./img/products/DayTruyenDong/W-8.jpg",
            img: "./img/products/DayTruyenDong/W-8(2).jpg",
            key: "W-8",
            thickness: "0.7 mm",
            width: "320 mm",
          },
        ],
        type: 2,
      },
      {
        id: 4,
        name: "TC-20EF",
        img: "./img/products/DayTruyenDong/TC-20EF_.jpg",
        children: [
          {
            idProduct: 4,
            name: "TC-20EF",
            img2: "./img/products/DayTruyenDong/TC-20EF_.jpg",
            img: "./img/products/DayTruyenDong/TC-20EF.jpg",
            key: "TC-20EF",
            thickness: "2.0 mm",
            width: "500 mm",
          },
        ],
        type: 2,
      },
      {
        id: 5,
        name: "S-1, S-2, S-3",
        img: "./img/products/DayTruyenDong/S-2_S-3.jpg",
        children: [
          {
            idProduct: 5,
            name: "S-1",
            img2: "./img/products/DayTruyenDong/S-2_S-3.jpg",
            img: "./img/products/DayTruyenDong/S-2_S-3(1).jpg",
            key: "S-1",
            thickness: "1.5 mm",
            width: "250 mm",
          },
          {
            idProduct: 5,
            name: "S-2",
            img2: "./img/products/DayTruyenDong/S-2_S-3.jpg",
            img: "./img/products/DayTruyenDong/S-2_S-3(1).jpg",
            key: "S-2",
            thickness: "2.0 mm",
            width: "250 mm",
          },
          {
            idProduct: 5,
            name: "S-3",
            img2: "./img/products/DayTruyenDong/S-2_S-3.jpg",
            img: "./img/products/DayTruyenDong/S-2_S-3(1).jpg",
            key: "S-3",
            thickness: "3.0 mm",
            width: "200 mm",
          },
        ],
        type: 2,
      },
      {
        id: 6,
        name: "TC-2, TC-3, S-391H",
        img: "./img/products/DayTruyenDong/TC-3_.jpg",
        children: [
          {
            idProduct: 6,
            name: "TC-2",
            img2: "./img/products/DayTruyenDong/TC-3_.jpg",
            img: "./img/products/DayTruyenDong/TC-3.jpg",
            key: "TC-2",
            thickness: "2.0 mm",
            width: "250 mm",
          },
          {
            idProduct: 6,
            name: "TC-3",
            img2: "./img/products/DayTruyenDong/TC-3_.jpg",
            img: "./img/products/DayTruyenDong/TC-3.jpg",
            key: "TC-3",
            thickness: "3.0 mm",
            width: "200 mm",
          },
          {
            idProduct: 6,
            name: "S-391H",
            img2: "./img/products/DayTruyenDong/TC-3_.jpg",
            img: "./img/products/DayTruyenDong/TC-3.jpg",
            key: "S-391H",
            thickness: "4.0 mm",
            width: "150 mm",
          },
        ],
        type: 2,
      },
      {
        id: 7,
        name: "X-30, X-40, X-60",
        img: "./img/products/DayTruyenDong/X40.jpg",
        children: [
          {
            idProduct: 7,
            name: "X-30",
            img2: "./img/products/DayTruyenDong/X40.jpg",
            img: "./img/products/DayTruyenDong/X40(1).jpg",
            key: "X-30",
            thickness: "3.0 mm",
            width: "150 mm",
          },
          {
            idProduct: 7,
            name: "X-40",
            img2: "./img/products/DayTruyenDong/X40.jpg",
            img: "./img/products/DayTruyenDong/X40(1).jpg",
            key: "X-40",
            thickness: "4.0 mm",
            width: "150 mm",
          },
          {
            idProduct: 7,
            name: "X-60",
            img2: "./img/products/DayTruyenDong/X40.jpg",
            img: "./img/products/DayTruyenDong/X40(1).jpg",
            key: "X-60",
            thickness: "6.0 mm",
            width: "150 mm",
          },
        ],
        type: 2,
      },
      {
        id: 8,
        name: "LA-1",
        img: "./img/products/DayTruyenDong/LA-1_.jpg",
        children: [
          {
            idProduct: 8,
            name: "LA-1",
            img2: "./img/products/DayTruyenDong/LA-1_.jpg",
            img: "./img/products/DayTruyenDong/LA-1.jpg",
            key: "LA-1",
            thickness: "6.0 mm",
            width: "150 mm",
          },
        ],
        type: 2,
      },
      {
        id: 9,
        name: "Dây Phi",
        img: "./img/products/DayTruyenDong/DayPhi.jpg",
        children: [
          {
            idProduct: 9,
            name: "Dây Phi",
            img: "./img/products/DayTruyenDong/DayPhi.jpg",
            key: "Dây Phi",
          },
        ],
        type: 2,
      },
    ],
  },
];

loadDataProduct(data);
