const data = [
  {
    title: "Sản phẩm PU răng",
    type: 1,
    data: [
      {
        id: 1,
        name: "3M, 5M, 8M, 14M",
        img: "./img/products/PURang/3M.jpg",
        children: [
          {
            idProduct: 1,
            name: "3M",
            img: "./img/products/PURang/specifications HTD.png",
            img2: "./img/products/PURang/3M.jpg",
            key: "3M",
            P: "3.0 mm",
            H: "2.4 mm",
            Ht: "1.22 mm",
          },
          {
            idProduct: 1,
            name: "5M",
            img2: "./img/products/PURang/5M.jpg",
            img: "./img/products/PURang/specifications HTD.png",
            key: "5M",
            P: "5.0 mm",
            H: "3.6 mm",
            Ht: "2.1 mm",
          },
          {
            idProduct: 1,
            name: "8M",
            img2: "./img/products/PURang/8M.jpg",
            img: "./img/products/PURang/specifications HTD.png",
            key: "8M",
            P: "8.0 mm",
            H: "5.6 mm",
            Ht: "3.9 mm",
          },
          {
            idProduct: 1,
            name: "14M",
            img2: "./img/products/PURang/14M.jpg",
            img: "./img/products/PURang/specifications HTD.png",
            key: "14M",
            P: "14.0 mm",
            H: "10.0 mm",
            Ht: "6.1 mm",
          },
        ],
        type: 2,
      },
      {
        id: 2,
        name: "S5M, S5M-black, S8M, S8M-black, S8M-green",
        img: "./img/products/PURang/S5M.jpg",
        children: [
          {
            idProduct: 2,
            name: "S5M",
            img2: "./img/products/PURang/S5M.jpg",
            img: "./img/products/PURang/specifications SM.png",
            key: "S5M",
            P: "5.0 mm",
            H: "3.4 mm",
            Ht: "1.9 mm",
          },
          {
            idProduct: 2,
            name: "S5M-black",
            img2: "./img/products/PURang/S5M-PAZ_.jpg",
            img: "./img/products/PURang/specifications SM.png",
            key: "S5M-PAZ-Black",
            P: "5.0 mm",
            H: "3.4 mm",
            Ht: "1.9 mm",
          },
          {
            idProduct: 2,
            name: "S8M",
            img2: "./img/products/PURang/S8M.jpg",
            img: "./img/products/PURang/specifications SM.png",
            key: "S8M",
            P: "8.0 mm",
            H: "5.2 mm",
            Ht: "2.95 mm",
          },
          {
            idProduct: 2,
            name: "S8M-black",
            img2: "./img/products/PURang/S8M-PAZ-BLACK_.jpg",
            img: "./img/products/PURang/specifications SM.png",
            key: "S8M-PAZ-Black",
            P: "8.0 mm",
            H: "5.2 mm",
            Ht: "2.95 mm",
          },
          {
            idProduct: 2,
            name: "S8M-green",
            img2: "./img/products/PURang/S8MPAZ.jpg",
            img: "./img/products/PURang/specifications SM.png",
            key: "S8M-PAZ-Green",
            P: "8.0 mm",
            H: "5.2 mm",
            Ht: "2.95 mm",
          },
        ],
        type: 2,
      },
      {
        id: 3,
        name: "T5, T10, T10-green, T20",
        img: "./img/products/PURang/T10.jpg",
        children: [
          {
            idProduct: 3,
            name: "T5",
            img2: "./img/products/PURang/T5.jpg",
            img: "./img/products/PURang/specifications T.png",
            key: "T5",
            P: "5.0 mm",
            H: "2.2 mm",
            Ht: "1.2 mm",
          },
          {
            idProduct: 3,
            name: "T10",
            img2: "./img/products/PURang/T10.jpg",
            img: "./img/products/PURang/specifications T.png",
            key: "T10",
            P: "10.0 mm",
            H: "4.5 mm",
            Ht: "2.5 mm",
          },
          {
            idProduct: 3,
            name: "T10-green",
            img2: "./img/products/PURang/T10PAZ_.jpg",
            img: "./img/products/PURang/specifications T.png",
            key: "T10-PAZ-PAR",
            P: "10 mm",
            H: "4.5 mm",
            Ht: "2.5 mm",
          },
          {
            idProduct: 3,
            name: "T20",
            img2: "./img/products/PURang/T20.jpg",
            img: "./img/products/PURang/specifications T.png",
            key: "T20",
            P: "20 mm",
            H: "8.0 mm",
            Ht: "5.0 mm",
          },
        ],
        type: 2,
      },
      {
        id: 4,
        name: "AT5, AT10, AT20",
        img: "./img/products/PURang/AT5.jpg",
        children: [
          {
            idProduct: 4,
            name: "AT5",
            img2: "./img/products/PURang/AT5.jpg",
            img: "./img/products/PURang/specifications AT.png",
            key: "AT5",
            P: "5.0 mm",
            H: "2.7 mm",
            Ht: "1.2 mm",
            W: "2.5 mm",
          },
          {
            idProduct: 4,
            name: "AT10",
            img2: "./img/products/PURang/AT10.jpg",
            img: "./img/products/PURang/specifications AT.png",
            key: "AT10",
            P: "10.0 mm",
            H: "4.5 mm",
            Ht: "2.5 mm",
            W: "5.0 mm",
          },
          {
            idProduct: 4,
            name: "AT20",
            img2: "./img/products/PURang/AT20.jpg",
            img: "./img/products/PURang/specifications AT.png",
            key: "AT20",
            P: "20.0 mm",
            H: "8.0 mm",
            Ht: "5.0 mm",
            W: "10.0 mm",
          },
        ],
        type: 2,
      },
      {
        id: 5,
        name: "L, XL, H, XH",
        img: "./img/products/PURang/L.jpg",
        children: [
          {
            idProduct: 5,
            name: "L",
            img2: "./img/products/PURang/L.jpg",
            img: "./img/products/PURang/specifications L.png",
            key: "L",
            P: "9.252 mm",
            H: "3.6 mm",
            Ht: "1.9 mm",
            W: "3.25 mm",
          },
          {
            idProduct: 5,
            name: "XL",
            img2: "./img/products/PURang/XL.jpg",
            img: "./img/products/PURang/specifications L.png",
            key: "XL",
            P: "5.08 mm",
            H: "2.3 mm",
            Ht: "1.27 mm",
            W: "1.37 mm",
          },
          {
            idProduct: 5,
            name: "H",
            img2: "./img/products/PURang/H.jpg",
            img: "./img/products/PURang/specifications L.png",
            key: "H",
            P: "12.7 mm",
            H: "4.3 mm",
            Ht: "2.29 mm",
            W: "4.43 mm",
          },
          {
            idProduct: 5,
            name: "XH",
            img2: "./img/products/PURang/XH.jpg",
            img: "./img/products/PURang/specifications L.png",
            key: "XH",
            P: "22.225 mm",
            H: "11.2 mm",
            Ht: "6.35 mm",
            W: "7.94 mm",
          },
        ],
        type: 2,
      },
    ],
  },
];

loadDataProduct(data);
